name: 'Hackathon Submission'
description: 'Submit your project for the Uniswap AI Hackathon'
title: '[SUBMISSION] '
labels: ['hackathon-submission']
body:
  - type: input
    id: project_name
    attributes:
      label: 'Project Name'
      placeholder: 'My Awesome Project'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'Describe your project. '
      placeholder: 'What does your project do? What problem does it solve?'
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 'Category'
      options:
        - DeFi Automation
        - Developer Tooling
        - Social/Community
        - Other
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### Team Lead Contact (Required for KYC / Prize Distribution)
        Prizes are paid in USDC. We need the following for KYC verification of the team lead.

  - type: input
    id: first_name
    attributes:
      label: 'First Name'
      description: 'Team lead first name (required for KYC)'
      placeholder: 'Jane'
    validations:
      required: true

  - type: input
    id: last_name
    attributes:
      label: 'Last Name'
      description: 'Team lead last name (required for KYC)'
      placeholder: 'Doe'
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: 'Email'
      description: 'Team lead email address (required for KYC)'
      placeholder: 'jane@example.com'
    validations:
      required: true

  - type: input
    id: wallet_address
    attributes:
      label: 'Wallet Address'
      description: 'EVM wallet address for prize distribution (optional)'
      placeholder: '0x...'

  - type: markdown
    attributes:
      value: '---'

  - type: input
    id: team_members
    attributes:
      label: 'Team Members'
      description: 'Comma-separated GitHub usernames'
      placeholder: '@username1, @username2'
    validations:
      required: true

  - type: input
    id: repo_url
    attributes:
      label: 'GitHub Repository'
      description: "URL to your project's GitHub repository"
      placeholder: 'https://github.com/org/repo'
    validations:
      required: true

  - type: input
    id: demo_url
    attributes:
      label: 'Demo URL'
      description: 'Optional: URL to a live demo or video'
      placeholder: 'https://example.com/demo'

  - type: input
    id: tech_stack
    attributes:
      label: 'Technical Stack'
      description: 'Comma-separated technologies used'
      placeholder: 'TypeScript, React, Uniswap SDK, ...'
    validations:
      required: true
