# Composite action to validate skills across all plugins
# Scans each plugin's skills/ directory, validates SKILL.md frontmatter
# and checks consistency between plugin.json declarations and skill directories

name: 'Validate Skills'
description: 'Validates that all plugin skills have valid SKILL.md files with required frontmatter'

inputs:
  plugins-dir:
    description: 'Path to the plugins directory (scans all plugin.json files within)'
    required: false
    default: 'packages/plugins'

outputs:
  skill-count:
    description: 'Number of skills validated'
    value: ${{ steps.validate.outputs.skill_count }}

runs:
  using: 'composite'
  steps:
    - name: Validate skills
      id: validate
      shell: bash
      env:
        PLUGINS_DIR: ${{ inputs.plugins-dir }}
      run: |
        echo "=== Validating Skills ==="
        echo ""

        TOTAL_ERRORS=0
        TOTAL_SKILLS=0
        RESULTS=""

        # --- Pass 1: Collect all skill names across all plugins ---
        # This ensures prerequisite checks work regardless of plugin processing order
        ALL_SKILL_NAMES=""
        for pjson in "$PLUGINS_DIR"/*/.claude-plugin/plugin.json; do
          [ -f "$pjson" ] || continue
          PLUGIN_DIR=$(dirname "$(dirname "$pjson")")
          SKILLS_DIR="$PLUGIN_DIR/skills"
          [ -d "$SKILLS_DIR" ] || continue
          for entry in "$SKILLS_DIR"/*/; do
            [ -d "$entry" ] || continue
            ALL_SKILL_NAMES="$ALL_SKILL_NAMES$(basename "$entry")"$'\n'
          done
        done

        # --- Pass 2: Validate each plugin's skills ---
        for pjson in "$PLUGINS_DIR"/*/.claude-plugin/plugin.json; do
          [ -f "$pjson" ] || continue
          PLUGIN_DIR=$(dirname "$(dirname "$pjson")")
          PLUGIN_NAME=$(basename "$PLUGIN_DIR")

          echo "--- Plugin: $PLUGIN_NAME ---"

          # Get skills declared in plugin.json
          DECLARED_SKILLS=$(jq -r '.skills[]?' "$pjson" 2>/dev/null | sed 's|.*/||')

          # Check each declared skill directory exists
          for SKILL_NAME in $DECLARED_SKILLS; do
            [ -z "$SKILL_NAME" ] && continue
            SKILL_DIR="$PLUGIN_DIR/skills/$SKILL_NAME"

            if [ ! -d "$SKILL_DIR" ]; then
              echo "::error::Skill '$SKILL_NAME' declared in $PLUGIN_NAME/plugin.json but directory not found: $SKILL_DIR"
              TOTAL_ERRORS=$((TOTAL_ERRORS + 1))
              RESULTS="$RESULTS| $PLUGIN_NAME/$SKILL_NAME | Missing directory | - | - | - | - |\n"
            fi
          done

          # Scan actual skills/ directory for skill directories
          SKILLS_DIR="$PLUGIN_DIR/skills"
          [ -d "$SKILLS_DIR" ] || continue

          for entry in "$SKILLS_DIR"/*/; do
            [ -d "$entry" ] || continue
            SKILL_NAME=$(basename "$entry")
            TOTAL_SKILLS=$((TOTAL_SKILLS + 1))

            # Check SKILL.md exists
            SKILL_MD="$entry/SKILL.md"
            if [ ! -f "$SKILL_MD" ]; then
              echo "::error::No SKILL.md found in $PLUGIN_NAME/skills/$SKILL_NAME"
              TOTAL_ERRORS=$((TOTAL_ERRORS + 1))
              RESULTS="$RESULTS| $PLUGIN_NAME/$SKILL_NAME | Missing SKILL.md | - | - | - | - |\n"
              continue
            fi

            # --- Frontmatter validation ---
            FRONTMATTER=$(awk '/^---$/{if(++c==2) exit} c==1' "$SKILL_MD")

            FM_NAME=$(echo "$FRONTMATTER" | grep '^name:' | head -1 | sed 's/^name:[[:space:]]*//' || true)
            FM_DESC=$(echo "$FRONTMATTER" | grep '^description:' | head -1 | sed 's/^description:[[:space:]]*//' || true)
            FM_LICENSE=$(echo "$FRONTMATTER" | grep '^license:' | head -1 | sed 's/^license:[[:space:]]*//' || true)
            FM_AUTHOR=$(echo "$FRONTMATTER" | grep '^[[:space:]]*author:' | head -1 | sed 's/^[[:space:]]*author:[[:space:]]*//' || true)

            HAS_NAME="yes"
            HAS_DESC="yes"
            HAS_LICENSE="yes"
            HAS_AUTHOR="yes"

            if [ -z "$FM_NAME" ]; then
              echo "::error::Missing 'name' in frontmatter: $SKILL_MD"
              TOTAL_ERRORS=$((TOTAL_ERRORS + 1))
              HAS_NAME="no"
            fi

            if [ -z "$FM_DESC" ]; then
              echo "::error::Missing 'description' in frontmatter: $SKILL_MD"
              TOTAL_ERRORS=$((TOTAL_ERRORS + 1))
              HAS_DESC="no"
            fi

            if [ -z "$FM_LICENSE" ]; then
              echo "::error::Missing 'license' in frontmatter: $SKILL_MD"
              TOTAL_ERRORS=$((TOTAL_ERRORS + 1))
              HAS_LICENSE="no"
            fi

            if [ -z "$FM_AUTHOR" ]; then
              echo "::error::Missing 'metadata.author' in frontmatter: $SKILL_MD"
              TOTAL_ERRORS=$((TOTAL_ERRORS + 1))
              HAS_AUTHOR="no"
            fi

            # --- Name consistency ---
            if [ -n "$FM_NAME" ] && [ "$FM_NAME" != "$SKILL_NAME" ]; then
              echo "::error::Frontmatter name '$FM_NAME' does not match directory name '$SKILL_NAME'"
              TOTAL_ERRORS=$((TOTAL_ERRORS + 1))
            fi

            # --- Prerequisite existence ---
            PREREQ_LINE=$(echo "$FRONTMATTER" | grep 'prerequisites:' | head -1 | sed 's/.*prerequisites:[[:space:]]*//' || true)
            PREREQS=""
            if [ -n "$PREREQ_LINE" ]; then
              PREREQS="$PREREQ_LINE"
            else
              PREREQS=$(echo "$FRONTMATTER" | awk '
                /prerequisites:/ { found=1; next }
                found && /^[[:space:]]*- / { gsub(/^[[:space:]]*- /, ""); print; next }
                found { exit }
              ' || true)
            fi

            for prereq in $PREREQS; do
              if [ -n "$prereq" ] && ! echo "$ALL_SKILL_NAMES" | grep -qx "$prereq"; then
                echo "::error::Prerequisite '$prereq' not found across plugins for skill $PLUGIN_NAME/$SKILL_NAME"
                TOTAL_ERRORS=$((TOTAL_ERRORS + 1))
              fi
            done

            # --- Check skill is declared in plugin.json ---
            if [ -n "$DECLARED_SKILLS" ] && ! echo "$DECLARED_SKILLS" | grep -qx "$SKILL_NAME"; then
              echo "::warning::Skill '$SKILL_NAME' exists in $PLUGIN_NAME/skills/ but not declared in plugin.json"
            fi

            if [ "$HAS_NAME" = "yes" ] && [ "$HAS_DESC" = "yes" ] && [ "$HAS_LICENSE" = "yes" ] && [ "$HAS_AUTHOR" = "yes" ]; then
              STATUS="Passed"
            else
              STATUS="Failed"
            fi
            RESULTS="$RESULTS| $PLUGIN_NAME/$SKILL_NAME | $STATUS | $HAS_NAME | $HAS_DESC | $HAS_LICENSE | $HAS_AUTHOR |\n"

            echo "  $SKILL_NAME: name=$HAS_NAME desc=$HAS_DESC license=$HAS_LICENSE author=$HAS_AUTHOR"
          done
        done

        echo ""
        echo "=== Validation Summary ==="
        echo "Total skills: $TOTAL_SKILLS"
        echo "Errors: $TOTAL_ERRORS"

        # Set outputs
        echo "skill_count=$TOTAL_SKILLS" >> "$GITHUB_OUTPUT"

        # Create job summary
        {
          echo "## Skills Validation"
          echo ""
          echo "| Skill | Status | Has Name | Has Description | Has License | Has Author |"
          echo "|-------|--------|----------|-----------------|-------------|------------|"
          echo -e "$RESULTS"
          echo ""
          echo "**Summary:** $TOTAL_SKILLS skill(s) checked, $TOTAL_ERRORS error(s)"
        } >> "$GITHUB_STEP_SUMMARY"

        if [ $TOTAL_ERRORS -gt 0 ]; then
          echo "::error::$TOTAL_ERRORS error(s) found during skills validation"
          exit 1
        fi

        echo "All skills validated successfully!"
